version: "3.9"

services:
  client:
    image: ${DOCKERHUB_USERNAME}/client-cms-${SAFE_TITRE_SITE}:latest
    container_name: client
    ports:
      - "80:8080"
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - monitoring

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "2020:2020"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
