version: "3.9"

services:
  client:
    image: ${DOCKERHUB_USERNAME}/client-cms-${SAFE_TITRE_SITE}:latest
    container_name: client
    ports:
      - "80:80"
    networks:
      - monitoring

#
#
#  client-dev:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    ports:
#      - 3000:3000
#    volumes:
#      - .:/app
#      - /app/node_modules
#    environment:
#      NODE_ENV: development
#      HOST: 0.0.0.0

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
    ports:
      - "2020:2020"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=:9100'

networks:
  monitoring:
    driver: bridge
